<?php
/**
 * Block editor script dependencies and version.
 *
 * Normally generated by @wordpress/scripts during the build process.
 * Since this block uses no JSX or ES modules, it is maintained manually.
 *
 * @package CityCore
 */
return array(
	'dependencies' => array( 'wp-blocks', 'wp-element', 'wp-i18n' ),
	'version'      => '0.1.0',
);
